### ISSUE TITLE
Bug in library, gets casts to Integer and can overflow

### ISSUE THREAD

**Issue by 18316614989** [obstrom/packer-app-api#3]
this bug how solved it?

**Comment by obstrom** [comment]
Hi,

This error is due to a dependency on [3d-bin-container-packing](https://github.com/skjolber/3d-bin-container-packing). 

At the time of the last update to this repo there was a [bug in 3d-bin-container-packing](https://github.com/skjolber/3d-bin-container-packing/issues/512) which would cause larger numbers to overflow. So if you tried to pack boxes with large dimensions, you would get this error.

This has since been fixed in 3d-bin-container-packing with version `2.0.10` and newer. Updating this dependency in `build.gradle` to this version, or newer, should fix this. 

https://github.com/obstrom/packer-app-api/blob/162ea5791c609e1e1d5f2b79fa92a484620dd144/build.gradle#L35

**Comment by 18316614989** [comment]
thanks ,
I've read the "3d-bin-container-packing"  and updated my system`s dependency version of 2.1.4 in maven ,thanks for your reply.

**Comment by obstrom** [comment]
@18316614989 did this solve your issue?

**Comment by 18316614989** [comment]
I use a large number of boxes to pack, it returns empty and can not generate models, how do you solve it, or do you have a way to solve the problem of packing returns empty, I can pay your solution fee, what do you think?

**Comment by obstrom** [comment]
In this specific demo project there is a hard-coded limit on the number of boxes/containers to accept, which is currently set to 5. This was done since I found it to be the simplest way to control bad packing behavior when introducing too many containers. You can change this by editing this line:
https://github.com/obstrom/packer-app-api/blob/cb2a7b8cd788d4becd996ca2aaa1785f5632191c/src/main/java/com/obstrom/packerservice/core/packer/Packager.java#L67

Be aware that using a large number of containers could impact performance and packing accuracy- at least it did with version `2.0.9` of `3d-bin-container-packing`. Perhaps this has been improved?

If the packing still returns empty it likely means that `3d-bin-container-packing` found no valid way to pack the requested order (bug or no bug), or an error occurred within that library.

Apologies, but I do not currently accept work by commission. Feel free to fork or use this project as a basis for whatever work you want to do. I would recommend building something new based on either `3d-bin-container-packing` or another library, since this is just a simple demo API.

**Comment by 18316614989** [comment]
Oh, that's a shame. Thank you for your reply. I wish you a happy life and come to Guangzhou, Guangdong Province, South China, when you have time. If you are free to come, you can contact me by email is 18316614989@163.com or by phone with WeChat is 18316614989, waiting for you, I am Joe Cheung.
